[colors.bright]
black = "0x45475a"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xffffff"
yellow = "0xf9e2af"

[colors.normal]
black = "0x1e1e2e"
blue = "0x89b4fa"
cyan = "0x94e2d5"
green = "0xa6e3a1"
magenta = "0xf5c2e7"
red = "0xf38ba8"
white = "0xcdd6f4"
yellow = "0xf9e2af"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[font]
size = 18.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 6
y = 6

[terminal]
